Data:
  data_root:  ../data/VOCdevkit2012/VOC2012
  train_list: ./lists/pascal/voc_sbd_merge_noduplicate.txt
  val_list:  ./lists/pascal/val.txt
  classes: 16


Train:
  # Aug
  train_h: 417
  train_w: 417
  val_size: 417
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 255
  padding_label: 255
  # Dataset & Mode
  split: 0
  data_set: 'pascal'
  use_split_coco: False # True means FWB setting
  # Optimizer
  batch_size: 3 # batch size for training (bs12 for 1GPU)
  base_lr: 2.5e-4
  epochs: 100
  start_epoch: 0
  stop_interval: 75 # stop when the best result is not updated for "stop_interval" epochs
  index_split: 0 # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  warmup: False
  # Viz & Save & Resume
  print_freq: 10
  save_freq: 10
  resume: # path to latest checkpoint (default: none, such as epoch_10.pth)  
  # Validate
  evaluate: True
  fix_random_seed_val: True
  batch_size_val: 6
  resized_val: True
  ori_resize: False  # use original label for evaluation
  # Else
  workers: 8  # 8 data loader workers
  manual_seed: 321
  seed_deterministic: False
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]

Method:
  layers: 50
  vgg: False



## deprecated multi-processing training
# Distributed:
#   dist_url: tcp://127.0.0.1:6789
#   dist_backend: 'nccl'
#   multiprocessing_distributed: False
#   world_size: 1
#   rank: 0
#   use_apex: False
#   opt_level: 'O0'
#   keep_batchnorm_fp32:
#   loss_scale:

